### ISSUE TITLE
Embedded credentials deprecated in June 2017

### ISSUE THREAD

**Issue by elgalu** [zalando/chrome-oauth-bearer-plugin#11]
Hi, I upgraded to master branch today and now in Chrome (unstable channel) Version 58.0.3000.4 dev (Linux 64-bit) I'm getting this *warning*

> Subresource requests whose URLs contain embedded credentials (e.g. `https://user:pass@host/`) are deprecated, and will be blocked in M59, around June 2017. See https://www.chromestatus.com/feature/5669008342777856 for more details.

![image](https://cloud.githubusercontent.com/assets/111569/22642489/2fde71b4-ec5b-11e6-9879-ac3d22692751.png)

**Comment by elgalu** [comment]
FYI Still works well on Chrome Version 57.0.2987.21 beta (Linux 64-bit)

**Comment by elgalu** [comment]
But seems to be just a warning

**Comment by pragmader** [comment]
We can use [this API](https://developer.mozilla.org/en/docs/Web/API/WindowBase64/Base64_encoding_and_decoding) for base64 encoding and put it as `Authorization: <base64(login:password)>` header to the XHR.

**Comment by gilvegliach** [comment]
@elgalu @pragmader Thanks guys, I'll take a look!

**Comment by pragmader** [comment]
@gilvegliach not a big deal, I've created a [PR](https://github.com/zalando/chrome-oauth-bearer-plugin/pull/12) for this.

**Comment by gilvegliach** [comment]
Fixed by #12

**Comment by dragonnn** [comment]
Is they any chance to use the header in javascript for opening a new window or creating an iframe? I use this options in my system with urls and I am not happy with removing it...

**Comment by pragmader** [comment]
@dragonnn Could you please provide with more details about your use-case of the extension? Frankly, I don't see any obvious connection between iframes or windows opening and the authorization header.

**Comment by dragonnn** [comment]
Well in my system I have some parts of it with should be visible/accessible only for certain users. And now I am just using iframe or window.open with url user:password@host:/partforthisuser maybe it isn't that best idea but this worked fine without any additional logic need on the backend :/.

**Comment by pragmader** [comment]
@dragonnn but in which part was the extension was? I'm just trying to understand how the change affects your use-case, sounds like you're not using the extension at all.

**Comment by pragmader** [comment]
@dragonnn no problem, sorry for not being helpful. I've found [the same question](http://stackoverflow.com/questions/4325968/window-open-with-headers) you've asked and it seems like we can't specify headers using `window.open`
