### ISSUE TITLE
Special characters like exclamation marks are not supported in passwords 

### ISSUE THREAD

**Issue by Retro64** [zalando/chrome-oauth-bearer-plugin#2]
In background.js function fetchtoken at least password (and maybe even userName) should be substituted by escaped version(s):

xhr.open('GET', authUrl, true, escape(userName), escape(password));

**Comment by hjacobs** [comment]
Hmm, would need to check whether this is correct

**Comment by Retro64** [comment]
At least exclamation marks within passwords break the send GET requests due they are pasted plain to the request

**Comment by LappleApple** [comment]
Hey @hjacobs, were you ever able to check on this? Perhaps we can re-label so someone else can pick up the work.

**Comment by Retro64** [comment]
FYI: I still use the "fixed" version locally and it is still working flawless.

**Comment by LappleApple** [comment]
@Retro64 Thank you for that note. Do you recommend any action on this thread, then? If not, we could close.

**Comment by Retro64** [comment]
I still recommend to insert the escaping in the function as there is no restriction in using special characters like exclamation marks within the password. These would still break the GET requests without escaping.

**Comment by hjacobs** [comment]
@Retro64 can you do a PR please?
